# These limits are used by MoveIt
/**:
  ros__parameters:
    robot_description_planning:
      joint_limits:
        # The gripper max velocity is so slow that acceleration approximates instantaneous
        # Add these placeholders to silence the warning
        primary_ar_gripper_body_finger1:
          has_acceleration_limits: true
          max_acceleration: 1.0
        primary_ar_gripper_body_finger2:
          has_acceleration_limits: true
          max_acceleration: 1.0
